### ISSUE TITLE
bluez-es vs bluer

### ISSUE THREAD

**Issue by igiona** [bluez-rs/bluez-async#267]
Hi, I stumbled across this library and I wondered how does this library differs from the "Official BlueZ Bindings for Rust" 
https://github.com/bluez/bluer and why should one use this one instead of the official one?

**Comment by qwandor** [comment]
Hi there,
The first release of `bluez-async` was on 8th January 2021, whereas the first release of `bluer` was on 6th July 2021, so if you want to know why `bluer` was created as a separate library rather than contributing to `bluez-async` you'll need to ask the authors of `bluer`.

At the time that we started developing `bluez-async` there were no async Rust Bluetooth libraries for Linux. We started off using `blurz`, but the blocking interface was not suitable for our applications so we developed this instead.

In terms of functionality, `bluez-async` is currently focussed on BLE central functionality, mostly around GATT, whereas `bluer` includes a range of other APIs such as GATT peripheral support, L2CAP, RFCOMM and mesh. `bluez-async` has an event API designed to make it easy to handle a large number of connected peripherals simultaneously sending notifications, as the original use-case we designed it for ([mijia-homie](https://github.com/alsuren/mijia-homie/)) involves managing lots of sensors connected to a single central. `bluer` seems to be designed more for working with a single peripheral at a time.

**Comment by igiona** [comment]
Thank you @qwandor for the explanation. ~Please note that with my question I was not trying to blame anyone. It was a genuine attempt to understand the differences between the two implementations.~

As far as I can see, `bluer` seems to have implemented an async interface as well https://github.com/bluez/bluer/blob/master/bluer%2Fexamples%2Fgatt_client.rs

**Comment by qwandor** [comment]
Yes, `bluer` is also async. `blurz` is an earlier library which is not, and was the inspiration for `bluez-async`.

The main API difference between `bluer` and `bluez-async` is that `bluer` seems to give you a separate stream of events per peripheral or characteristic or whatever, whereas `bluez-async` gives you the option of having a single stream of events for all peripherals. In my opinion and experience this makes it easier to write programs which need to manage a large number of peripherals at once.
